### ISSUE TITLE
Consider using workbox-window

### ISSUE THREAD

**Issue by jeffposnick** [pwa-builder/pwa-update#1]
This is obviously optional, but given that there is some overlap between this component and Workbox, one have you considered using [`workbox-window`](https://developers.google.com/web/tools/workbox/modules/workbox-window) to handle the registration and listening for updates?

The new `messageSkipWaiting()` method we [have planned](https://github.com/GoogleChrome/workbox/issues/2394) could be used directly.

CC: @philipwalton

**Comment by jgw96** [comment]
Thanks again! So the reason I decided not to use the workbox-window library is we wanted to keep this component free of any workbox deps. However, i definitely think it makes sense to standardize on the same event name (:  .Im going to close this one for now and will track changing the event name on #2 .
