### ISSUE TITLE
How to define Scope for Service Worker

### ISSUE THREAD

**Issue by radenkozec** [pwa-builder/pwa-update#14]
I found code for installation like this which have scope:
navigator.serviceWorker.register('pwabuilder-sw.js', {
    scope: './'
  })

**I use your project to register service worker but I am not sure how to define scope?**

Currently I have Manifest and ServiceWorker in wwwroot of application start_url = "/" and my app still does not recognize serviceWorker

**Comment by lee-leonardo** [comment]
@radenkozec I see you're missing a forward slash in the path of the navigator.serviceWorker.register url.

The registration requires either an absolute or a url that is relative to the default base url.

**Comment by radenkozec** [comment]
@lee-leonardo I am not using pwa-builder anymore. Nobody responded for months...
