### ISSUE TITLE
Not working with .NET Core 

### ISSUE THREAD

**Issue by radenkozec** [pwa-builder/pwa-update#15]
When I use this code 👍 
```
<script
  type="module"
  src="https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate"
></script>

<pwa-update></pwa-update>
```
to register PWA in _layout root file of website it works only on home page https://somesite.com.
If I go to https://somesite.com/something
I am getting error that serviceworker cannot be registered.

My start_url='/' and service worker is in wwwroot folder of application.

**Comment by radenkozec** [comment]
Update: I have manage to create workaround by checking in _Layout if I am in home page and only then to call your code.
Not sure is this correct way to do it? Thanks

**Comment by lee-leonardo** [comment]
@radenkozec do you still need help? I'm not familiar with .NET Core, but I know someone who is.

**Comment by radenkozec** [comment]
Not using PWA-Builder anymore
