### ISSUE TITLE
[Question] How to force auto update ?

### ISSUE THREAD

**Issue by neoteknic** [pwa-builder/pwa-update#19]
Maybe bad documentation, but no example to force auto update ? Attribute forceupdate maybe ?

**Comment by nPaul** [comment]
check everytime with setInterval
or hook on router navigation change
any idea?

**Comment by lee-leonardo** [comment]
@neoteknic and @nPaul 
The `updateevent` string allows you to control the name of the event that you can send the component to trigger an force update.

**Comment by ilivewithian** [comment]
@lee-leonardo I'm reading the updated docs, but I'm not understanding how to implement what you're describing.

`<pwa-update updateevent="ermmm"></pwa-update>`
