### ISSUE TITLE
Match the SKIP_WAITING message that Workbox uses

### ISSUE THREAD

**Issue by jeffposnick** [pwa-builder/pwa-update#2]
Given that there's some reliance on Workbox already, it would be 👍 to consider matching the format for the `SKIP_WAITING` message that's [used in Workbox](https://github.com/GoogleChrome/workbox/blob/4f4f97743ed18edd92306d08cb453757e9537c1e/packages/workbox-build/src/templates/sw-template.js#L34-L38).

The listener would look like:

```
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
```

And the `window` client code would either send something like `postMessage({type: 'SKIP_WAITING'})`, or you could get that same type of message by using `workbox-window` (see #1).

CC: @philipwalton

**Comment by jgw96** [comment]
Thanks! As discussed in the above linked issue I have made this change here https://github.com/pwa-builder/pwa-update/commit/85eea7c8ef35a9fcc81f25d3749cf987d65c6a31 .
