### ISSUE TITLE
How to set z-index on component?

### ISSUE THREAD

**Issue by nPaul** [pwa-builder/pwa-update#20]
message UPDATE showing under component Vue PWA app
need to set z-index to 100

**Comment by nPaul** [comment]
maybe monkey way
but i do this that
create pwa-update.scss
 pwa-update::part(updateToast) {
     z-index: 100;
     top: 16px;
     bottom: auto;
 }

**Comment by lee-leonardo** [comment]
@nPaul yeah if you need to manually set the CSS of a web component, the part selector is a pretty typical way of doing it.
