### ISSUE TITLE
Fix pwa-update demo link/Create a demo for pwa-update

### ISSUE THREAD

**Issue by christianliebel** [pwa-builder/pwa-update#6]
**Describe the bug**

Link to the `pwa-update` demo app on the README page leads to a wrong demo.

**To Reproduce**

1. Go to https://github.com/pwa-builder/pwa-update
2. Click on https://glitch.com/~pwainstall
3. It should show a `pwa-update` demo, but instead it shows a `pwa-install` demo.

**Expected behavior**

It should show a `pwa-update` demo.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jgw96** [comment]
Fixed here https://github.com/pwa-builder/pwa-update/commit/b882f936d80fff76c8e523589cb00636f00f5936 thank you!
