### ISSUE TITLE
"An update is available" shows when refreshing the page

### ISSUE THREAD

**Issue by JudahGabriel** [pwa-builder/pwa-update#7]
Using the new service workers results in "an update is available" toast showing whenever the page is refreshed.

Repro:
Go to https://www.pwabuilder.com/serviceworker
Hit F5

The "update is available" toast will always show, even though there's no update available.

**Comment by JudahGabriel** [comment]
Also looks like it happens on page navigation:

Go to pwabuilder.com
Then in the address bar, type pwabuidler.com/serviceworker

As the page navigates, the "update is available" toast shows.

**Comment by lee-leonardo** [comment]
This doesn't seem to be happening anymore.
