### ISSUE TITLE
Update toast should used fixed positioning

### ISSUE THREAD

**Issue by JudahGabriel** [pwa-builder/pwa-update#8]
When an update toast appears, it's currently used absolute positioning to place the toast at the bottom right. 

However, if the toast appears on a scrollable page, and the user scrolls down, the toast now appears in the middle of the page, e.g. 

![image](https://user-images.githubusercontent.com/312936/81882576-f0990c00-9547-11ea-8190-ef5cfc7bdc4b.png)

**Comment by lee-leonardo** [comment]
@JudahGabriel looks fixed, I don't have access to this repo to close this out.

**Comment by lee-leonardo** [comment]
https://github.com/pwa-builder/pwa-update/pull/11
